# 配置组一             端口类
mixed-port: 7890
redir-port: 7891
tproxy-port: 1536

# 配置组二             代理类
allow-lan: true
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
# https://github.com/Loyalsoldier/v2ray-rules-dat 的复刻 https://github.com/DustinWin/ruleset_geodata 
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/DustinWin/ruleset_geodata/releases/download/clash/geoip-all.metadb"
  geosite: "https://mirror.ghproxy.com/https://github.com/DustinWin/ruleset_geodata/releases/download/clash/geosite-all.dat"
unified-delay: true
tcp-concurrent: true
enable-process: true
external-controller: 0.0.0.0:9090
#面板默认Meta 可选Yacd 清除浏览器缓存即可重新加载
external-ui: /data/adb/box_bll/panel/Yacd/ #/Meta #/Yacd
secret: ""


# 配置组三           选择类
mode: Rule
# silent 静默，不输出
# error 仅输出发生错误至无法使用的日志
# warning 输出发生错误但不影响运行的日志，以及 error 级别内容
# info 输出一般运行的内容，以及 error 和 warning 级别的日志
# debug 尽可能的输出运行中所有的信息
log-level: silent
# 可选："chrome", "firefox", "safari", "iOS", "android", "edge", "360"," qq", "random"
# 若选择 "random", 则按 Cloudflare Radar 数据按概率生成一个现代浏览器指纹。
global-client-fingerprint: random # 随机指纹 （全局客户端指纹）
# 控制是否让 Clash 去匹配进程
# always 开启，强制匹配所有进程
# strict 默认，由 Clash 判断是否开启
# off 不匹配进程，推荐在路由器上使用此模式
find-process-mode: always

#####################
#修改配置文件保存时，建议重启模块服务/重载配置.
#####################

profile:
    # 储存 API 对策略组的选择，以供下次启动时使用
  store-selected: true
  # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - google.com
    - +.v2ex.com
  # # 白名单,跳过嗅探结果
  skip-domain:
    - Mijia Cloud
    - +.apple.com

tun:
  enable: false #true 开 #false 关
  device: tun0
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
  route-exclude-address:
  - 192.168.0.0/16
  - fc00::/7
  exclude-package:
  - com.tencent.mm
  - com.tencent.tmgp.sgame
  - com.miui.weather2
  - com.ss.android.ugc.aweme
  - com.xiaomi.market
  - com.android.providers.downloads.ui

dns:
  enable: true
  prefer-h3: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
    - '+.leigod.com'
    - '+.vivox.com'
    - '+.stun.+'
    - '.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - 'lens.l.google.com'
    - '*.mcdn.bilivideo.cn'
    - "connect.rom.miui.com"
    - 'localhost.ptlogin2.qq.com'
    - WORKGROUP
  default-nameserver:
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853
    - https://223.5.5.5/dns-query 
    - 119.29.29.29
    - 223.6.6.6 
    - system 
  nameserver:
    - quic://dns.adguard.com:784
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://sm2.doh.pub/dns-query
    - QUIC://dns.alidns.com/dns-query
    - https://mozilla.cloudflare-dns.com/dns-query
    - https://[2400:3200::1]/dns-query#skip-cert-verify=true
    - dhcp://en0

  p: &p
    {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
  u: &u
    use:
    - 1.主要地址
    - 2.备用地址

proxy-providers:
  1.主要地址:
    <<: *p
    url: "引入您的Clash订阅链接地址"
    path: ./proxy_providers/subscribe1.yaml
    
  2.备用地址:
    <<: *p
    url: "https://qslink.yeahfast.com/verival/qsy/lod?token=iNRzCUaMQLrjzgG0"
    path: ./proxy_providers/subscribe2.yaml
    
proxies:
  - {name: 🌎 全球直连, type: direct, udp: true}
  - {name: DNS_Hijack, type: dns}
proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [♻️ 主要延迟最低,♻️ 备用延迟最低,🌎 全球直连], <<: *u}
  - {name: ♻️ 主要延迟最低, use: [1.主要地址], type: url-test}
  - {name: ♻️ 备用延迟最低, use: [2.备用地址], type: url-test}

  ######################  建议代理  ######################
  - {name: 📢 GFW, type: select, proxies: [🚀 节点选择,🌎 全球直连,♻️ 主要延迟最低,♻️ 备用延迟最低], <<: *u}
  - {name: 📲 电报信息, type: select, proxies: [🚀 节点选择,🌎 全球直连,♻️ 主要延迟最低,♻️ 备用延迟最低], <<: *u}

  - {name: Ⓜ️ 微软服务, type: select, proxies: [🚀 节点选择,🌎 全球直连,♻️ 主要延迟最低,♻️ 备用延迟最低], <<: *u}
  - {name: 🍎 苹果服务, type: select, proxies: [🚀 节点选择,🌎 全球直连,♻️ 主要延迟最低,♻️ 备用延迟最低], <<: *u}
  - {name: 🎹 网易音乐「进程匹配」, type: select, proxies: [🌎 全球直连,🚀 节点选择,♻️ 主要延迟最低,♻️ 备用延迟最低]}
  - {name: 🛑 广告拦截, type: select, proxies: [REJECT,🌎 全球直连]}
  - {name: 🐋 漏网之鱼, type: select, proxies: [🚀 节点选择,🌎 全球直连,♻️ 主要延迟最低,♻️ 备用延迟最低], <<: *u}
rule-providers:
  ##################  代理，直连，广告  ###################
  proxy: # 代理域名列表
    type: http
    behavior: domain
    path: ./rule/proxy.yaml
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/proxy.yaml"
    interval: 86400
  direct: # 直连域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./rule/direct.yaml
    interval: 86400
  cncidr: # 中国大陆 IP 地址列表
    type: http
    behavior: ipcidr
    url: "https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./rule/cncidr.yaml
    interval: 86400
  private: # 私有网络专用域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/private.yaml"
    path: ./rule/private.yaml
    interval: 86400
  lancidr: # 局域网 IP 及保留 IP 地址列表 
    type: http
    behavior: ipcidr
    url: "https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./rule/lancidr.yaml
    interval: 86400
  ads: # 广告域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/ads.yaml"
    path: ./rule/ads.yaml
    interval: 86400
  ######################  特定域名  ######################
  gfw: # GFWList 域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./rule/gfw.yaml
    interval: 86400
  telegramip:
    type: http
    behavior: ipcidr
    path: ./rule/telegramip.yaml
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/telegramip.yaml"
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Microsoft.yaml
    url: "https://raw.githubusercontent.com/MoGuangYu/rules/main/Home/Microsoft.yaml"
    interval: 86400
  Apple:
    type: http
    behavior: domain
    path: ./rule/Apple.yaml
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/apple-cn.yaml"
    interval: 86400

rules:
  # 基本规则
  - RULE-SET,lancidr,DIRECT # 局域网 IP 及保留 IP 地址列表
  - RULE-SET,private,DIRECT # 私有网络专用域名列表
  - GEOSITE,private,DIRECT   # 主流 Clash dashboard 在线面板域名
  ## fix dnsleak
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - IP-CIDR,28.0.0.1/8,REJECT,no-resolve
  - IP-CIDR6,::1/128,REJECT,no-resolve  
  ## direct FCM
  - AND,((NETWORK,TCP),(DST-PORT,5228-5230)),DIRECT
  - AND,((NETWORK,TCP),(DST-PORT,5228-5230),(OR,((DOMAIN-KEYWORD,google)))),DIRECT
  ## direct ntp
  - AND,((NETWORK,UDP),(DST-PORT,123)),DIRECT
  - DST-PORT,123/136/137-139,DIRECT,udp
  #########################  自写规则  #########################
  - DST-PORT,53,DNS_Hijack
  - AND,((PROCESS-NAME,mihomo),(NOT,((IN-TYPE,inner)))),REJECT
  - AND,((PROCESS-NAME,clash),(NOT,((IN-TYPE,inner)))),REJECT
  - PROCESS-NAME,com.netease.cloudmusic,🎹 网易音乐「进程匹配」

  - RULE-SET,telegramip,📲 电报信息,no-resolve
  - RULE-SET,Apple,🍎 苹果服务
  - RULE-SET,Microsoft,Ⓜ️ 微软服务
  - RULE-SET,gfw,📢 GFW

  - DOMAIN-SUFFIX,o33249.ingest.sentry.io,REJECT  # OPENAI 跟踪域名 reject
  - DOMAIN-SUFFIX,openaicom.imgix.net,REJECT  # OPENAI 跟踪域名 reject

  - RULE-SET,ads,🛑 广告拦截
  - GEOSITE,category-ads-all,🛑 广告拦截
  - RULE-SET,direct,🌎 全球直连
  - RULE-SET,cncidr,🌎 全球直连
  - GEOSITE,CN,🌎 全球直连
  - GEOIP,CN,🌎 全球直连,no-resolve
  - GEOIP,private,🌎 全球直连,no-resolve
  - RULE-SET,proxy,🚀 节点选择
  - MATCH,🐋 漏网之鱼
