# 代理提供者在下#############################################
proxy-providers:
  "主要订阅":      # 一号订阅链接
    type: http         
    path: ./provide/sub1.yaml # 默认只允许存储在 mihomo 的 Home Dir，如果想存储到任意位置，添加环境变量 SKIP_SAFE_PATH_CHECK=1
    url: "订阅链接"               # 此处填写订阅url
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600
  "备用订阅":
    type: http
    url: "订阅链接"
    interval: 3600
    path: ./provide/sub2.yaml
    # filter: 'xxx' # Supports regular expressions to filter by node name
    # exclude-filter: 'ctb' # Supports regular expressions to exclude based on node name
    # exclude-type: 'ss|http' # Does not support regular expressions, separated by '|', excluded by node type
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 3600
# 代理提供者在上############################################

# 配置组一             端口类
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 9797
tproxy-port: 9898


# 配置组二            布尔类
ipv6: false
allow-lan: true
tcp-concurrent: true
unified-delay: true
# 更改geoip使用文件,mmdb或者dat,true为dat
geodata-mode: true # 是否启用 geodata 规则集和geodata都启用
geo-auto-update: true # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时
keep-alive-interval: 1800  # 减少移动端设备耗电


# 配置组三           选择类
mode: rule  # rule（默认） global（需要在GLOBAL策略组选择）direct 
# silent 静默，不输出
# error 仅输出发生错误至无法使用的日志
# warning 输出发生错误但不影响运行的日志，以及 error 级别内容
# info 输出一般运行的内容，以及 error 和 warning 级别的日志
# debug 尽可能的输出运行中所有的信息
log-level: silent
# 可选："chrome", "firefox", "safari", "iOS", "android", "edge", "360"," qq", "random"
# 若选择 "random", 则按 Cloudflare Radar 数据按概率生成一个现代浏览器指纹。
global-client-fingerprint: random # 随机指纹 （全局客户端指纹）
# 可选的加载模式如下
# standard：标准加载器
# memconservative：专为内存受限(小内存)设备优化的加载器(默认值)
geodata-loader: memconservative
# 控制是否让 Clash 去匹配进程
# always 开启，强制匹配所有进程
# strict 默认，由 Clash 判断是否开启
# off 不匹配进程，推荐在路由器上使用此模式
find-process-mode: strict
bind-address: '*'


# 外部控制 (API)
# 外部控制器，可以使用 RESTful API 来控制你的 Clash 内核；API 监听地址，你可以将 127.0.0.1 修改为 0.0.0.0 来监听所有 IP；访问地址：http://127.0.0.1:9090
external-controller: 0.0.0.0:9090 
# secret: "123456" # API 的访问密钥 默认不添加
external-ui: /data/adb/box/clash/dashboard # 外部用户界面路径，可以为绝对路径，或者 Clash 工作目录的相对径
# external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip" # 自定义外部用户界面下载地址 
# tcp-concurrent: false
# tls:
  # certificate: string # 证书 PEM 格式，或者 证书的路径
  # private-key: string # 证书对应的私钥 PEM 格式，或者私钥路径

hosts:
  time.facebook.com: 17.253.84.125
  time.android.com: 17.253.84.125
  '*.mihomo.dev': 127.0.0.1
  '.dev': 127.0.0.1
  'alpha.mihomo.dev': '::1'
  test.com: [1.1.1.1, 2.2.2.2]
  home.lan: lan # lan 为特别字段，将加入本地所有网卡的地址
  # 只允许配置一个别名
# 目前仅用于 API 的 https

# https://github.com/Loyalsoldier/v2ray-rules-dat 的复刻 https://github.com/DustinWin/ruleset_geodata 
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/DustinWin/ruleset_geodata/releases/download/clash/geoip-all.metadb"
  geosite: "https://mirror.ghproxy.com/https://github.com/DustinWin/ruleset_geodata/releases/download/clash/geosite-all.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/DustinWin/ruleset_geodata/releases/download/clash/Country-all.mmdb"

profile:
  store-selected: true
  # 储存 API 对策略组的选择，以供下次启动时使用
  store-fake-ip: true
  # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址

sniffer:                           #【Meta专属】sniffer域名嗅探器
  enable: false                    # 嗅探器开关
  # # 开启后对 redir-host 类型识别的流量进行强制嗅探
  # # 包含 Tun、Redir 和 TProxy 或 DNS 为 redir-host
  force-dns-mapping: false
  parse-pure-ip: false           # 对所有未获取到域名的流量进行强制嗅探
  override-destination: false      # 是否使用嗅探结果作为实际访问,默认 true
  # # 全局配置,优先级低于 sniffer.sniff 实际配置
  sniff: # TLS 默认如果不配置 ports 默认嗅探 443
    TLS:
      ports: [443, 8443]
    HTTP: # 需要嗅探的端口, 默认嗅探 80
      ports: [80, 8080-8880]
      override-destination: true # 可覆盖 sniffer.override-destination
    QUIC:
      ports: [ 443 ]
  force-domain:
    - google.com
    - +.v2ex.com
  # # 白名单,跳过嗅探结果
  skip-domain:
    - Mijia Cloud
    - +.apple.com
  sniffing:
    - tls
    - http
  port-whitelist:
    - "80"
    - "443"

tun:
  enable: true
  device: utun # gvisor/mixed
  mtu: 9000 # 最大传输单元
  stack: system # gvisor / lwip / system
  dns-hijack: # dns 劫持，将匹配到的连接导入内部 dns 模块，不书写协议则为 udp://
    - udp://any:53  # 需要劫持的 DNS
    - tcp://any:53
  auto-route: true # 配置路由表
  auto-detect-interface: true  # 自动识别出口网卡
  endpoint-independent-nat: false # 启用独立于端点的 NAT,性能可能会略有下降,所以建议在需要的时候开启
  inet4-route-exclude-address: #启用 auto-route 时排除自定义网段
    - 192.168.0.0/16
  inet6-route-exclude-address: #启用 auto-route 时排除自定义网段
    - fc00::/7
  inet4-route-address: # 启用 auto-route 时使用自定义路由而不是默认路由
    - 0.0.0.0/1
    - 128.0.0.0/1
  inet6-route-address: # 启用 auto-route 时使用自定义路由而不是默认路由
    - "::/1"
    - "8000::/1"
   # strict-route: true # 将所有连接路由到 tun 来防止泄漏，但你的设备将无法其他设备被访问 热点将无法共享网络
  include_android_user:
    - 0
    # 多开用户
   #  include_package:
   #    - com.android.chrome
  # exclude_package:
    # - com.tencent.mm #  没必要开

dns:
  cache-algorithm: arc # ARC（Adaptive Replacement Cache）缓存算法
  enable: true  # 使用clashDNS
  # dns 服务监听
  listen: 0.0.0.0:1053
  use-hosts: true
  # 可选值 true/false
  # 是否解析 IPV6, 如为 false, 则回应 AAAA 的空解析
  ipv6: true
  ipv6-timeout: 300  # 单位：ms，内部双栈并发时，向上游查询 AAAA 时，等待 AAAA 的时间，默认 100ms
  # 可选值 true/false
  prefer-h3: true # 是否开启 DOH 的 http/3。 
  # 可选值 fake-ip / redir-host
  # Clash 的 dns 处理模式
  enhanced-mode: fake-ip
  # 格式为 ip/掩码
  # fakeip 下的 IP 段设置，tun 网卡的默认 ip 也使用此值
  fake-ip-range: 198.18.0.1/16
  # fakeip 过滤，以下地址不会下发 fakeip 映射用于连接
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
    - '+.leigod.com'
    - '+.vivox.com'
    - '+.stun.+'
    - '.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - 'lens.l.google.com'
    - '*.mcdn.bilivideo.cn'
    - 'localhost.ptlogin2.qq.com'
    - WORKGROUP

# 只能使用纯 IP 地址，可使用加密 DNS 想要DNS不泄露就用加密DNS
  # 默认的域名解析服务器，如不配置 fallback/proxy-server-nameserver , 则所有域名都由 nameserver 解析
  nameserver:    # 主要 国内代理
    - quic://dns.adguard.com:784#🌏 快速选择代理  # DNS over QUIC 测试
    - https://1.1.1.1/dns-query#🌏 快速选择代理
    - https://1.0.0.1/dns-query#🌏 快速选择代理
    - tls://223.5.5.5:853##🌏 快速选择代理 # DNS over TLS
    - https://doh.pub/dns-query##🌏 快速选择代理 # DNS over HTTPS
    - https://dns.alidns.com/dns-query##🌏 快速选择代理&h3=true # 强制 HTTP/3，与 perfer-h3 无关，强制开启 DoH 的 HTTP/3 支持，若不支持将无法使用
    - https://mozilla.cloudflare-dns.com/dns-query##🌏 快速选择代理&h3=true # 指定策略组和使用 HTTP/3
    - dhcp://en0#🌏 快速选择代理  # dns from dhcp #测试
 #   - tls://dns.google:853
 #   - tls://8.8.8.8:853
 #   - tls://8.8.4.4:853
 #   - tls://dns.alidns.com
 #   - tls://223.5.5.5
 #   - tls://223.6.6.6
 #   - tls://dot.pub
 #   - tls://1.12.12.12
 #   - tls://120.53.53.53
 #   - https://dns.google/dns-query
 #   - https://8.8.8.8/dns-query
 #   - https://8.8.4.4/dns-query
 #   - https://dns.alidns.com/dns-query
 #   - https://223.5.5.5/dns-query
 #   - https://223.6.6.6/dns-query
 #   - https://doh.pub/dns-query
 #   - https://1.12.12.12/dns-query
 #   - https://120.53.53.53/dns-query
 #   - 'tls://8.8.4.4#dns'
 #   - 'tls://1.0.0.1#dns'
 #   - 'tls://[2001:4860:4860::8844]#dns'
 #   - 'tls://[2606:4700:4700::1001]#dns'
  
  # 默认 dns, 用于解析 DNS 服务器 的域名
  # 只能使用纯 IP 地址，可使用加密 DNS
  default-nameserver: 
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853
    - https://223.5.5.5/dns-query 
    - tcp://119.29.29.29
    - tcp://223.6.6.6 
    - system 
    
  # 指定域名查询的解析服务器，可使用 geosite, 优先于 nameserver/fallback 查询
  # Note: 并发查询，无法保证顺序，以下仅作为书写演示，建议根据自己需求写
  nameserver-policy:
    "geosite:cn,private":
      - https://223.5.5.5/dns-query
      - https://doh.pub/dns-query
      - https://doh.360.cn/dns-query
      - tls://223.5.5.5
      - tls://dot.pub
    "rule-set:direct,private,apple":
      - https://223.5.5.5/dns-query
      - https://doh.pub/dns-query
      - https://doh.360.cn/dns-query
      - tls://223.5.5.5
      - tls://dot.pub         

  # 代理节点域名解析服务器，仅用于解析代理节点的域名
  proxy-server-nameserver:
  #  - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query
    - tls://223.5.5.5
    - tls://dot.pub     
  
  # 后备域名解析服务器，一般情况下使用境外 DNS, 保证结果可信
  # 配置 fallback后默认启用 fallback-filter,geoip-code为 cn
  fallback:
   #- tls://8.8.4.4
    - quic://a.passcloud.xyz:784#🌏 快速选择代理 # quic是新兴的，比tls快一倍
    - tls://8.8.4.4:853#🌏 快速选择代理
    - tcp://1.1.1.1#🌏 快速选择代理
    - https://1.1.1.1/dns-query#🌏 快速选择代理&h3=true
    - https://1.0.0.1/dns-query#🌏 快速选择代理
    - tls://1dot1dot1dot1.cloudflare-dns.com#🌏 快速选择代理 
  
  # 后备域名解析服务器筛选，满足条件的将使用 fallback结果或只使用 fallback解析
  fallback-filter:    # 国外网站使用此解析
    geoip: true # 配置是否使用 geoip
    geoip-code: CN
    # geosite 列表的内容被视为已污染，匹配到 geosite 的域名，将只使用 fallback解析，不去使用 nameserver
    geosite:      # 根据实际情况决定
      - cn
      - games-cn
      - apple-cn
      - microsoft-cn
    # 这些网段的结果会被视为污染，nameserver解析出这些结果时将会采用 fallback的解析结果
    ipcidr:
      - 240.0.0.0/4
    # 这些域名被视为已污染，匹配到这些域名，会直接使用 fallback解析，不去使用 nameserver
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.googleapis.+'    


# 第二部分 代理组配置  

proxies: 
  - {name: 🌎 全球直连, type: direct, udp: true}
proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [♻️ 延迟最低,🌎 全球直连], use: [主要订阅,备用订阅]}
  - {name: ♻️ 延迟最低, type: url-test, use: [主要订阅,备用订阅]}

  - {name: 📢 GFW, type: select, proxies: [🚀 节点选择,♻️ 延迟最低,🌎 全球直连], use: [主要订阅,备用订阅]}

  - {name: 🎮 国内游戏, type: select, proxies: [🌎 全球直连,🚀 节点选择,♻️ 延迟最低], use: [主要订阅,备用订阅]}
  - {name: Ⓜ️ 微软服务, type: select, proxies: [🌎 全球直连,🚀 节点选择,♻️ 延迟最低], use: [主要订阅,备用订阅]}
  - {name: 🍎 苹果服务, type: select, proxies: [🌎 全球直连,🚀 节点选择,♻️ 延迟最低], use: [主要订阅,备用订阅]}
  - {name: 🌎 国内网站, type: select, proxies: [🌎 全球直连,🚀 节点选择,♻️ 延迟最低], use: [主要订阅,备用订阅]}
  - {name: 🎹 网易音乐「进程匹配」, type: select, proxies: [🌎 全球直连,🚀 节点选择,♻️ 延迟最低], use: [主要订阅,备用订阅]}
  - {name: 🛑 广告拦截, type: select, proxies: [REJECT,🌎 全球直连]}
  - {name: 🐋 漏网之鱼, type: select, proxies: [🚀 节点选择,♻️ 延迟最低,🌎 全球直连], use: [主要订阅,备用订阅]}
  
      

# 第三部分 规则配置  

# 规则提供者在下
rule-providers: # https://github.com/Loyalsoldier/clash-rules 项目地址    另外一个规则库https://rules.xkww3n.cyou/   将在以后添加

################  特定域名  ################

  proxy: # 代理域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/proxy.yaml"
    path: ./ruleset/proxy.yaml
    interval: 86400

  apple: # Apple 在中国大陆可直连的域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/apple-cn.yaml"
    path: ./ruleset/apple.yaml
    interval: 86400

  Microsoft: # Apple 在中国大陆可直连的域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/MoGuangYu/rules@main/Home/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  google: # [慎用]Google 在中国大陆可直连的域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/google-cn.yaml"
    path: ./ruleset/google.yaml
    interval: 86400

  gfw: # GFWList 域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

################  直连列表  ################
  private: # 私有网络专用域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/private.yaml"
    path: ./ruleset/private.yaml
    interval: 86400

  lancidr: # 局域网 IP 及保留 IP 地址列表 
    type: http
    behavior: ipcidr
    url: "https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications: # 需要直连的常见软件列表
    type: http
    behavior: classical
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/applications.yaml"
    path: ./ruleset/applications.yaml
    interval: 86400

  direct: # 直连域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  cncidr: # 中国大陆 IP 地址列表
    type: http
    behavior: ipcidr
    url: "https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

################  其他规则  ################
  ads: # 广告域名列表
    type: http
    behavior: domain
    url: "https://fastly.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash-ruleset/ads.yaml"
    path: ./ruleset/ads.yaml
    interval: 86400




# 欢迎完善 DNS泄露的解决方案可以参考 dns设置 - https://1.1.1.1/dns-query#🌏 快速选择代理   注意后面的#🌏 快速选择代理

# 规则如下 顺序- 基本-自定义-特定网站-直连名单-拒绝名单-一般需要代理的网站-查漏补缺
# 规则如下！
rules:
  # 基本规则
  - RULE-SET,lancidr,DIRECT # 局域网 IP 及保留 IP 地址列表
  - RULE-SET,private,DIRECT # 私有网络专用域名列表
  - GEOSITE,private,DIRECT   # 主流 Clash dashboard 在线面板域名
  ## fix dnsleak
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
  - IP-CIDR,28.0.0.1/8,REJECT,no-resolve
  - IP-CIDR6,::1/128,REJECT,no-resolve  
  ## direct FCM
  - AND,((NETWORK,TCP),(DST-PORT,5228-5230)),DIRECT
  - AND,((NETWORK,TCP),(DST-PORT,5228-5230),(OR,((DOMAIN-KEYWORD,google)))),DIRECT
  ## direct ntp
  - AND,((NETWORK,UDP),(DST-PORT,123)),DIRECT
  - DST-PORT,123/136/137-139,DIRECT,udp

  # 自定义规则 高优先度
  # geosite 包含：fakeip-filter/private/ads/microsoft-cn/apple-cn/google-cn/games-cn/netflix/disney/max/primevideo/appletv/youtube/tiktok/bilibili/ai/networktest/proxy/cn
  # 特定网站集合
  - GEOSITE,games-cn,🎮 国内游戏
  - RULE-SET,gfw,📢 GFW
  - GEOSITE,apple-cn,🍎 苹果服务
  - RULE-SET,apple,🍎 苹果服务
  - RULE-SET,Microsoft,Ⓜ️ 微软服务
  - PROCESS-NAME,com.netease.cloudmusic,🎹 网易音乐「进程匹配」
  # 直连（或者断流）规则
  - RULE-SET,applications,🌎 国内网站
  - RULE-SET,direct,🌎 国内网站
  - RULE-SET,cncidr,🌎 国内网站
  - GEOSITE,cn,🌎 国内网站

  - DOMAIN-SUFFIX,o33249.ingest.sentry.io,REJECT  # OPENAI 跟踪域名 reject
  - DOMAIN-SUFFIX,openaicom.imgix.net,REJECT  # OPENAI 跟踪域名 reject

  - RULE-SET,ads,🛑 广告拦截
  - GEOSITE,ads,🛑 广告拦截

  # 一般需要代理的网站
  - RULE-SET,google,🚀 节点选择
  - RULE-SET,proxy,🚀 节点选择


  # 低优先度 匹配·漏网之鱼               
  - MATCH,🐋 漏网之鱼 # 收尾