mixed-port: 7890
redir-port: 7891
tproxy-port: 1536
mode: Rule
allow-lan: true
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash/geoip-all.metadb"
  geosite: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash/geosite-all.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/DustinWin/ruleset_geodata@clash/Country-all.mmdb"
unified-delay: true
tcp-concurrent: true
enable-process: true
log-level: silent
find-process-mode: always
global-client-fingerprint: chrome
external-controller: 0.0.0.0:9090
#面板默认Yacd 可选Meta 清除浏览器缓存即可重新加载
external-ui: /data/adb/box_bll/panel/Yacd/ #/Meta #/Yacd
secret: ""

#####################
#修改配置文件保存时，建议重启模块服务/重载配置.
#####################

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "Mijia Cloud"

tun:
  enable: false #true 开 #false 关
  device: tun0
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
  route-exclude-address:
  - 192.168.0.0/16
  - fc00::/7
  exclude-package:
  - com.tencent.mm
  - com.tencent.tmgp.sgame
  - com.miui.weather2
  - com.ss.android.ugc.aweme
  - com.xiaomi.market
  - com.android.providers.downloads.ui

dns:
  enable: true
  prefer-h3: true
  ipv6: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "connect.rom.miui.com"
    - "localhost.ptlogin2.qq.com"
  default-nameserver:
    - 119.29.29.29
    - 223.6.6.6
  nameserver:
    - QUIC://dns.alidns.com/dns-query
    - https://sm2.doh.pub/dns-query
    - https://[2400:3200::1]/dns-query#skip-cert-verify=true

  p: &p
    {type: http, interval: 86400, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 300}}
  u: &u
    use:
    - 1.主要地址
    - 2.备用地址

# 代理订阅地址
#############################################
proxy-providers:
  1.主要地址:
    <<: *p
    url: "引入您的Clash订阅链接地址"
    path: ./proxy_providers/subscribe1.yaml
    
  2.备用地址:
    <<: *p
    url: "https://qslink.yeahfast.com/verival/qsy/lod?token=iNRzCUaMQLrjzgG0"
    path: ./proxy_providers/subscribe2.yaml
#############################################
    
proxies:
  - {name: 🌎 全球直连, type: direct, udp: true}
  - {name: DNS_Hijack, type: dns}
proxy-groups:
  - {name: 🚀 节点选择, type: select, proxies: [♻️ 延迟最低,🌎 全球直连], <<: *u}
  - {name: ♻️ 延迟最低, <<: *u, type: url-test}
  - {name: 📱 脸书社交, type: select, proxies: [🚀 节点选择,♻️ 延迟最低,🌎 全球直连]}
  - {name: 📲 电报信息, type: select, proxies: [🚀 节点选择,♻️ 延迟最低,🌎 全球直连]}
  - {name: 🎬 油管媒体, type: select, proxies: [🚀 节点选择,♻️ 延迟最低,🌎 全球直连]}
  - {name: 📹 奈飞媒体, type: select, proxies: [🚀 节点选择,♻️ 延迟最低,🌎 全球直连]}
  - {name: 📢 谷歌服务, type: select, proxies: [🚀 节点选择,♻️ 延迟最低,🌎 全球直连]}
  - {name: Ⓜ️ 微软服务, type: select, proxies: [🚀 节点选择,♻️ 延迟最低,🌎 全球直连]}
  - {name: 🍎 苹果服务, type: select, proxies: [🚀 节点选择,♻️ 延迟最低,🌎 全球直连]}
  - {name: 🎮 Discord, type: select, proxies: [🚀 节点选择,♻️ 延迟最低,🌎 全球直连]}
  - {name: 📸 TikTok, type: select, proxies: [🚀 节点选择,♻️ 延迟最低,🌎 全球直连]}
  - {name: 🎹 网易音乐「进程匹配」, type: select, proxies: [🌎 全球直连,🚀 节点选择,♻️ 延迟最低]}
  - {name: 🛑 广告拦截, type: select, proxies: [REJECT,🌎 全球直连]}
  - {name: 🐋 漏网之鱼, type: select, proxies: [🚀 节点选择,🌎 全球直连]}
rule-providers:
  TikTok:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/TikTok.yaml
    url: "https://raw.githubusercontent.com/MoGuangYu/rules/main/Home/TikTok.yaml"
    interval: 86400
  Facebook:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Facebook.yaml
    url: "https://raw.githubusercontent.com/MoGuangYu/rules/main/Home/Facebook.yaml"
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Telegram.yaml
    url: "https://raw.githubusercontent.com/MoGuangYu/rules/main/Home/Telegram.yaml"
    interval: 86400
  YouTube:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/YouTube.yaml
    url: "https://raw.githubusercontent.com/MoGuangYu/rules/main/Home/YouTube.yaml"
    interval: 86400
  Google:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Google.yaml
    url: "https://raw.githubusercontent.com/MoGuangYu/rules/main/Home/Google.yaml"
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Microsoft.yaml
    url: "https://raw.githubusercontent.com/MoGuangYu/rules/main/Home/Microsoft.yaml"
    interval: 86400
  Apple:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Apple.yaml
    url: "https://raw.githubusercontent.com/MoGuangYu/rules/main/Home/Apple.yaml"
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Netflix.yaml
    url: "https://raw.githubusercontent.com/MoGuangYu/rules/main/Home/Netflix.yaml"
    interval: 86400
  Discord:
    type: http
    behavior: classical
    format: yaml
    path: ./rule/Discord.yaml
    url: "https://raw.githubusercontent.com/MoGuangYu/rules/main/Home/Discord.yaml"
    interval: 86400
rules:
  - DST-PORT,53,DNS_Hijack
  - AND,((PROCESS-NAME,mihomo),(NOT,((IN-TYPE,inner)))),REJECT
  - AND,((PROCESS-NAME,clash),(NOT,((IN-TYPE,inner)))),REJECT
  - PROCESS-NAME,com.netease.cloudmusic,🎹 网易音乐「进程匹配」
  - RULE-SET,Discord,🎮 Discord
  - RULE-SET,TikTok,📸 TikTok
  - RULE-SET,YouTube,🎬 油管媒体
  - RULE-SET,Netflix,📹 奈飞媒体
  - RULE-SET,Facebook,📱 脸书社交
  - RULE-SET,Google,📢 谷歌服务
  - RULE-SET,Apple,🍎 苹果服务
  - RULE-SET,Microsoft,Ⓜ️ 微软服务
  - RULE-SET,Telegram,📲 电报信息
  - GEOSITE,category-ads-all,🛑 广告拦截
  - GEOSITE,CN,🌎 全球直连
  - GEOIP,CN,🌎 全球直连,no-resolve
  - GEOIP,private,🌎 全球直连,no-resolve
  - MATCH,🐋 漏网之鱼
